### PR TITLE
Add support for URL redirection on form submission

### LINKED ISSUE #10: Render template or redirect at endpoint
For people not having js and therefore no async form submission the page might be nicer, if one renders a template or read a value from the form to redirect to.

For example a hidden field could contain the return page address, which mailout uses to redirect to.

### PR DESCRIPTION
**Pull request by witsch**
The `redirect_field` config option can be used to specify the name of a (hidden) form field, which may then contain a URL to redirect to after successful form submission.

Closes #10.

### CODE REVIEW

**Comment by SchumacherFM** [comment]
It looks like that I have forgotten this PR :-(
Will take a look later this week.

**Comment by witsch** [comment]
> It looks like that I have forgotten this PR :-(
> Will take a look later this week.

Cyrill, any chance to have a look at this perhaps? 🙂

**Review by SchumacherFM — APPROVED** [review]
lgtm

**Comment by SchumacherFM** [comment]
sorry that i have forgotten it :-( but now it is merged.

**Pull request merged**
